#+TITLE: Emacs Config
#+AUTHOR: Jack Burns
#+DATE: <2021-06-11 Fri>
#+OPTIONS: toc:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css"/>
#+PROPERTY: header-args:emacs-lisp :tangle ~/.doom.d/config.el


* Doom Emacs
I'm using doom-emacs which comes loaded with vim friendly keybinds and does some stuff under the hood to make emacs snappy. Highly recommend checking out the [[https://github.com/hlissner/doom-emacs][github]].
* Configuration
** Load Path
Where emacs looks for certain modules.
#+begin_src emacs-lisp
;;load path for manually installed packages
(add-to-list 'load-path "~/.doom.d/load_path/")
#+end_src
** Cosmetics
*** Theme
A nice theme.
#+begin_src emacs-lisp
;; Set the theme
(setq doom-theme 'doom-horizon)
#+end_src
*** Font
A nice font.
#+begin_src emacs-lisp
;;Font
(setq doom-font (font-spec :family "Iosevka" :size 13 :weight 'light)
      doom-variable-pitch-font (font-spec :family "Iosevka" :weight 'light))
#+end_src
*** Line numbers
I prefer relative line numbers with the current line-number showing the actual line.
#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src
** Org stuff
Org-mode is awesome! I use org-roam to easily navigate my org files and org-babel to easily manage a literate config.
*** Set org directory
#+begin_src emacs-lisp
;; Org settings
(setq org-directory "~/org-roam/")         ;; Location of org files
(setq org-roam-directory "~/org-roam")     ;; Set same as org-directory
(add-hook 'after-init-hook 'org-roam-mode) ;; Have org-roam mode on for org files
#+end_src
*** Org-bullets
Nice bullets for org mode instead of asterisks.
#+begin_src emacs-lisp
(require 'org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src
*** Org-babel code blocks
By typing "<el", a src block is automatically inserted.
#+begin_src emacs-lisp
;; Easy insertion of src blocks in org
(require 'org-tempo)
(add-to-list 'org-structure-template-alist '("sh" . "src shell"))
(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
(add-to-list 'org-structure-template-alist '("py" . "src python"))
#+end_src
*** Org-babel auto config
Defines a function which automatically exports the src from this file into our config.el.
#+begin_src emacs-lisp
;; Automatically tangle our Emacs.org config file when we save it
(defun efs/org-babel-tangle-config ()
  (when (string-equal (buffer-file-name)
                      (expand-file-name "~/org-roam/Dots/Emacs/config.org"))
    ;; Dynamic scoping to the rescue
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle))))

(add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'efs/org-babel-tangle-config)))
#+end_src
*** Org-babel languages
Define languages which can be evaluated in org buffers.
#+begin_src emacs-lisp
(org-babel-do-load-languages
  'org-babel-load-languages
  '((emacs-lisp . t)
    (python . t)))
(push '("conf-unix" . conf-unix) org-src-lang-modes)
#+end_src

** Keybinds
 My extra keybinds. Vterm is a fast shell in emacs.
#+begin_src emacs-lisp
;; My keybindings
(map! :leader
      :desc "Open vterm"
      "o t" #'vterm)            ;; my preferred terminal opens up like vscode
(map! :leader
      :desc "vterm/here"
      "o T" #'+vterm/here)

(map! :leader
      :desc "List bookmars"
      "o B" #'list-bookmarks)   ;; bookmarks are nice for things like your configuration

(map! :leader
      :desc "org-roam-find-file"
      "r f" #'org-roam-find-file)  ;; Show all of my org files nicely
                                   ;; org-raom allows search by tag functionallity
#+end_src
** Window Settings
*** Have split windows open to the right and down
#+begin_src emacs-lisp
(setq evil-split-window-below t
      evil-vsplit-window-right t)
#+end_src
** Python settings
*** LSP mode
Allows for syntax highlighting, autocompletion, and some other nice features.
#+begin_src emacs-lisp
(use-package python-mode
  :ensure t
  :hook (python-mode . lsp-deferred)) ;; Use a mspyls as backend for lsp mode.
#+end_src
*** Open python repl in the current window
#+begin_src emacs-lisp
(add-to-list 'display-buffer-alist
'("^\\*Python\\*$" . (display-buffer-same-window))) ;; open python buffer in current window
#+end_src
*** pydoc
Custom function to pull up funtion documentation of token under cursor.
#+begin_src emacs-lisp
(load "~/.doom.d/load_path/pydoc.el") ;; Custom fuction to find python function docs
                                                                    ;; under cursor
#+end_src
